# 🔐 Password Strength Prediction

### Machine Learning + NLP Project

This project analyzes password patterns and builds a machine learning model to classify passwords into three strength levels:

- **0 → Weak**
- **1 → Medium**
- **2 → Strong**

**Workflow:**  
Data Collection → Data Cleaning → EDA → Feature Engineering → NLP/TF-IDF → Model Training → Password Strength Prediction

# Getting Startred....

In [1]:
#import all the basic libraries ...
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

# Read the data from sql database...

In [3]:
import sqlite3

In [4]:
## u have your data into 'password_Data.sqlite' which has table  'Users' 
## now u can read data from this db file 'password_Data.sqlite' using sqlite3 & pandas

In [8]:
#first off all we have to create sql connection to the sql database
con = sqlite3.connect(r"password_data.sqlite")

In [9]:
'''check online its table name on https://sqliteonline.com/'''
data = pd.read_sql_query("SELECT * FROM  Users",con)

In [10]:
data.shape

(100000, 3)

In [11]:
data.head()

   index                 password  strength
0      0                zxe870819         1
1      1             xw46454nr23l         1
2      2                soporte13         1
3      3  accounts6000webhost.com         2
4      4                 c443balg         1

# 2.. Doing basic data cleaning !

In [12]:
data.columns

Index(['index', 'password', 'strength'], dtype='str')

### Removing ir-relevant features !

In [13]:
data.drop('index',axis = 1,inplace = True)

In [14]:
data.head()

                  password  strength
0                zxe870819         1
1             xw46454nr23l         1
2                soporte13         1
3  accounts6000webhost.com         2
4                 c443balg         1

### Check duplicate rows

In [17]:
data.duplicated().sum()

np.int64(0)

# check for missing values in the column....

In [19]:
data.isnull().sum()

password    0
strength    0
dtype: int64

In [22]:
data.isnull().any().sum() ## it means 0 feature have NAN value

np.int64(0)

# check datatype of every feature!

In [24]:
data.dtypes

password      str
strength    int64
dtype: object

### checking whether "strength" feature has ir-relevant values or not !

In [25]:
data['strength']

0        1
1        1
2        1
3        2
4        1
        ..
99995    1
99996    1
99997    1
99998    1
99999    1
Name: strength, Length: 100000, dtype: int64

In [26]:
data['strength'].unique()

array([1, 2, 0])

In [27]:
data['strength'].nunique()

3

# 3.. Performing Semantic Analysis !
    e.g ,,      
          
          a) How many password textual actually holds only numeric characters ?
          b) How many password textual actually holds only Upper-case character ? 
          
          c) How many password textual actually holds only alphabet ?
          d) How many password textual actually holds alpha-numeric character ? 
          e) How many password textual actually holds title-case character ? 
          
          f) How many password textual actually holds some special special character ?

In [28]:
data.columns

Index(['password', 'strength'], dtype='str')

In [29]:
data['password']

0                      zxe870819
1                   xw46454nr23l
2                      soporte13
3        accounts6000webhost.com
4                       c443balg
                  ...
99995                 obejofi215
99996                 fmiopvxb64
99997                  czvrbun38
99998                  mymyxe430
99999                glqjhkxb467
Name: password, Length: 100000, dtype: str

In [30]:
data['password'][0]

'zxe870819'

In [31]:
type(data['password'][0])

str

### a) How many password textual actually holds only numeric characters ?

In [35]:
data['password'].str.isnumeric()

0        False
1        False
2        False
3        False
4        False
         ...
99995    False
99996    False
99997    False
99998    False
99999    False
Name: password, Length: 100000, dtype: bool

In [36]:
data[data['password'].str.isnumeric()]

      password  strength
12280   943801         0
14992    12345         0
20958   147856         0
21671   140290         0
23269   123987         0
28569  1233214         0
31329  0159456         0
32574   363761         0
37855  4524344         0
43648  5521597         0
45271   626262         0
52266   156651         0
58717      369         0
59619   151106         0
67723     1234         0
68106  1995151         0
68592   112233         0
69255  9562489         0
74938       12         0
77298    18731         0
86406     1050         0
86608   158491         0
94908   060415         0
96459        1         0
98122  6975818         0
98248   454545         0

In [38]:
data[data['password'].str.isnumeric()].shape # only 26 people hav eset their password as number according to this scenario

(26, 2)

### b) How many password textual actually holds only Upper-case character ?

In [40]:
data[data['password'].str.isupper()]

          password  strength
115       EYT63119         1
273      INSPIRON6         1
338       1A2S3D4F         1
367      13269123A         1
373     YAMAZAKI82         1
...            ...       ...
99590   V13000993J         1
99692  65925013ABC         1
99784     01EDD055         1
99893     1UPONYOU         1
99910       UNION1         0

[1506 rows x 2 columns]

In [41]:
data[data['password'].str.isupper()].shape

(1506, 2)

### c) How many password textual actually holds only alphabet ?

In [43]:
data['password'].str.isalpha()

0        False
1        False
2        False
3        False
4        False
         ...
99995    False
99996    False
99997    False
99998    False
99999    False
Name: password, Length: 100000, dtype: bool

In [44]:
data[data['password'].str.isalpha()].shape

(50, 2)

### d) How many password textual actually holds alpha-numeric character ?

In [45]:
data['password'].str.isalnum()

0         True
1         True
2         True
3        False
4         True
         ...
99995     True
99996     True
99997     True
99998     True
99999     True
Name: password, Length: 100000, dtype: bool

In [46]:
data[data['password'].str.isalnum()].shape

(97203, 2)

### e) How many password textual actually holds title-case character ?

In [47]:
data['password'].str.istitle()

0        False
1        False
2        False
3        False
4        False
         ...
99995    False
99996    False
99997    False
99998    False
99999    False
Name: password, Length: 100000, dtype: bool

In [48]:
data[data['password'].str.istitle()].shape

(932, 2)

### f) How many password textual actually holds special character ?

In [49]:
data['password']

0                      zxe870819
1                   xw46454nr23l
2                      soporte13
3        accounts6000webhost.com
4                       c443balg
                  ...
99995                 obejofi215
99996                 fmiopvxb64
99997                  czvrbun38
99998                  mymyxe430
99999                glqjhkxb467
Name: password, Length: 100000, dtype: str

In [50]:
import string

In [52]:
string.punctuation ## all punctuations defined in "string" package !

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [69]:
def find_semantics(row):
    for char in row:
        if char in string.punctuation:
            return 1
        else:
            return 0

In [70]:
data['password'].apply(find_semantics)== 1

0        False
1        False
2        False
3        False
4        False
         ...
99995    False
99996    False
99997    False
99998    False
99999    False
Name: password, Length: 100000, dtype: bool

In [71]:
data[data['password'].apply(find_semantics)== 1]

                   password  strength
192      <html>13476590nosD         2
4218      !@#testdevdomain1         2
6915                 ]/=[;.         0
12897              *110528#         1
33035              *171078*         1
34621             @28031978         1
37196           *********33         1
39145        $j8g0R12218001         2
44007                ``````         0
61825      @ytu9z3pigx3c9m@         2
65083       @@000Ka6bE000.?         2
69158              ..932006         1
74795                (*)(^#         0
80832                +%&/()         0
85408                [fkzdf         0
90081             @veresiye         1
93780             #helenku#         1
94416  ///sekharbiswas70///         2
99064              ?}?êO/á         1

In [68]:
data[data["password"].apply(find_semantics)==1]

                      password  strength
3      accounts6000webhost.com         2
68                12463773800+         1
98                  p.r.c.d.g.         1
145                  cita-cita         1
180         karolina.susnina0U         2
...                        ...       ...
99748             maiselis.com         1
99845          hosting4meze!@#         2
99954         semista_bakung15         2
99980         halflife2010!LEB         2
99988                lbhtrnjh@         1

[2663 rows x 2 columns]

In [75]:
data[data["password"].apply(find_semantics)==1].shape
## ie , 2663 observations have special characters in between them ..
## 2.6% people password actually uses special character in their password ..
## and contains 19 rows and have 2 columns

(19, 2)

## 4.. Applying Feature Engineering !

In [76]:
'''

we have password strength so you can do a quick google search to check what features password depends on:-
It depends on 5 factors :

    Length of password
    Frequency of Lowercase Characters
    Frequency of Uppercase Characters
    Frequency of Numeric Characters
    Frequency of Special Characters

These will be the result of the google search to find factors effecting strength of password..


'''

'\n\nwe have password strength so you can do a quick google search to check what features password depends on:-\nIt depends on 5 factors :\n\n    Length of password\n    Frequency of Lowercase Characters\n    Frequency of Uppercase Characters\n    Frequency of Numeric Characters\n    Frequency of Special Characters\n\nThese will be the result of the google search to find factors effecting strength of password..\n\n\n'

#### length of every password

In [77]:
data['password'][0]

'zxe870819'

In [78]:
len(data['password'][0])

9

In [80]:
data['length'] = data['password'].str.len()

#### Frequency of Lowercase Characters :

In [86]:
password = "shan99"

In [87]:
[char for char in password if char.islower()]

['s', 'h', 'a', 'n']